version: "3.8"
services:
  db:
    image: postgres:14
    container_name: myanime_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    networks:
      - custom

  app:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: myanime_app
    command: "gunicorn --chdir ./src main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/fastapi_app
    networks:
      - custom

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: "npm start"
    depends_on:
      - app
    ports:
      - "3000:3000"
    networks:
      - custom

volumes:
  postgres_data:

networks:
  custom:
    driver: bridge
