version: "3.8"
services:
  db:
    image: postgres:14
    container_name: myanime_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - custom

volumes:
  postgres_data:

networks:
  custom:
    driver: bridge
