version: "3.8"
services:
  db:
    image: postgres:14
    container_name: myanime_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: myanime_app
    command: "gunicorn --chdir ./src main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/fastapi_app

volumes:
  postgres_data:
