"""Create User

Revision ID: 454461072839
Revises: 0e781517daa1
Create Date: 2024-09-27 10:32:32.651198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454461072839'
down_revision: Union[str, None] = '0e781517daa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.add_column('anime', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'anime', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'anime', type_='foreignkey')
    op.drop_column('anime', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
