"""empty message

Revision ID: 7e92c96e17ad
Revises: adeb6758c48c
Create Date: 2024-08-01 05:51:03.719972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e92c96e17ad'
down_revision: Union[str, None] = 'adeb6758c48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'anime', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anime', type_='unique')
    # ### end Alembic commands ###
