"""empty message

Revision ID: 0e781517daa1
Revises: de2431c3b7b0
Create Date: 2024-09-07 12:05:53.011988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e781517daa1'
down_revision: Union[str, None] = 'de2431c3b7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_start_end',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('anime_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('anime_from_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_from_to',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('anime_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.uuid'], name='anime_from_to_anime_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='anime_from_to_pkey')
    )
    op.drop_table('anime_start_end')
    # ### end Alembic commands ###
