"""Change anime name unique constraint

Revision ID: 237b849042ca
Revises: c43929553475
Create Date: 2024-10-17 15:21:58.813459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237b849042ca'
down_revision: Union[str, None] = 'c43929553475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('anime_name_key', 'anime', type_='unique')
    op.create_unique_constraint('anime_name_uc', 'anime', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('anime_name_uc', 'anime', type_='unique')
    op.create_unique_constraint('anime_name_key', 'anime', ['name'])
    # ### end Alembic commands ###
