"""empty message

Revision ID: adeb6758c48c
Revises: 
Create Date: 2024-08-01 05:07:35.238523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adeb6758c48c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('WATCHING', 'WATCHED', 'DROPPED', name='state'), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=4096), nullable=True),
    sa.Column('from_to', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime')
    # ### end Alembic commands ###
