name: Docker Image CI

on:
  push:
    paths: [ "backend/**", ".github/**" ]
  pull_request:
    paths: [ "backend/**", ".github/**" ]

jobs:

  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run test db with docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "backend/docker-compose-test.yml"
        services: |
          testdb

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install
      working-directory: backend

    - name: Test with pytest
      run: |
        py.test -v
      working-directory: backend
