name: Docker Image CI

on:
  push:
    paths: [ "backend/**", ".github/**" ]
  pull_request:
    paths: [ "backend/**", ".github/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "backend/docker-compose-test.yml"
        services: |
          testdb
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend
    - name: Test with pytest
      run: |
        pip install pytest
        py.test -v
      working-directory: backend
